### ISSUE TITLE
[Question] Are you looking to get this mainlined?

### ISSUE THREAD

**Issue by DerRidda** [ocerman/zenpower#1]
Thanks for providing this! Zen sensor support has been quite bad in Linux and this driver is certainly appreciated.

But seems to me that this driver should probably land in the kernel itself I wonder if you are trying to get it mainlined. Are you?

**Comment by ocerman** [comment]
Hello,

Yeah, I would like to see this merged into Linux kernel, but am I not pursuing this goal.

I am new to Linux development - I am not sure what conditions needs to be met before merging code to kernel, nor how to do it. I also cannot guarantee this driver will work with all Zen cpus as AMD did not publish documentation about SVI2 stuff for public and some of the code I got working only by trial-and-error testing with my hardware.
