### ISSUE TITLE
Upstreaming or merging with k10temp?

### ISSUE THREAD

**Issue by shmerl** [ocerman/zenpower#10]
Did you consider merging it with k10temp? There is no need to limit the later to temperature only.

**Comment by Venemo** [comment]
I'd also be interested to hear the answer to this.

**Comment by Venemo** [comment]
I guess this question might be a duplicate of #1

**Comment by ocerman** [comment]
No plans currently as I cannot guarantee that this driver will work with all Zen cpus.
