### ISSUE TITLE
Zenpower not showing frequencies

### ISSUE THREAD

**Issue by jave808** [ocerman/zenpower#30]
Have left debug data in other issue.

Zenpower was showing frequencies, now nothing.

.
![image](https://user-images.githubusercontent.com/65537119/82197167-f9ba1c80-993d-11ea-92ea-c27de1ae2806.png)

**Comment by birdie-github** [comment]
The zenpower driver doesn't provide this data. File a bug report against Zen Monitor instead.

https://github.com/ocerman/zenmonitor

**Comment by ocerman** [comment]
Hello, thx for your report. This issue is in zenmonitor app. It may be related to ocerman/zenmonitor#20
