### ISSUE TITLE
Ryzen 3000 series not working

### ISSUE THREAD

**Issue by ghost** [ocerman/zenpower#6]
I get the following output from lm_sensors on my Ryzen 7 3700x:
### zenpower-pci-00c3
```
Adapter: PCI adapter
SVI2_Core:    +1.55 V  
SVI2_SoC:     +1.55 V  
Tdie:          +0.0°C  (high = +70.0°C)
Tctl:          +0.0°C  
SVI2_P_Core:   0.00 W  
SVI2_P_SoC:    0.00 W  
SVI2_C_Core:  +0.00 A  
SVI2_C_SoC:   +0.00 A  
```

Do you have any documentation to help me test/code to get this working?

**Comment by ridobe** [comment]
Check out [this](https://github.com/ocerman/zenpower/issues/4) closed issue. It contains a link to the kernel patch you'll need.

**Comment by ghost** [comment]
Thanks ridobe, I'll try it out.

**Comment by ocerman** [comment]
I have added kernel patch link to the readme
